export const CURRENCY = 'CZK'
export const PRODUCT_DATA_NAME = 'TaskKy Pro'
export const PRODUCT_DATA_DESCRIPTION = 'Unlimited boards for your organization'
export const UNIT_AMOUNT = 20000
export const RECURRING_INTERVAL = 'month'
export const QUANTITY = 1
export const MODE = 'subscription'
export const PAYMENT_TYPES = 'card'
export const BILLING_ADDRESS_COLLECTION = 'auto'
